"""Rule-based response tables and lookup helpers for DecoBot."""

from __future__ import annotations

import random
import string


def expand_aliases(
    base: dict[str, str | list[str]],
    aliases: dict[str, tuple[str, ...]],
) -> dict[str, str | list[str]]:
    expanded: dict[str, str | list[str]] = dict(base)
    for canonical, alias_keys in aliases.items():
        value = base[canonical]
        for alias in alias_keys:
            expanded[alias] = value
    return expanded


def pick(responses: str | list[str]) -> str:
    if isinstance(responses, list):
        return random.choice(responses)
    return responses


def _normalise(text: str) -> str:
    lowered = text.lower().strip()
    no_punct = lowered.translate(str.maketrans("", "", string.punctuation))
    return " ".join(no_punct.split())


_BASE_RESPONSES: dict[str, str | list[str]] = {
    "hello": [
        "Hey there! 👋 I'm DecoBot. How can I help you today?",
        "Hello! DecoBot online and ready. What's on your mind?",
        "Hi! Great to see you. Ask me anything! 🤖",
    ],
    "hi": [
        "Hi! Great to see you. What's on your mind?",
        "Hey! How can I help?",
    ],
    "hey": "Hey! What can I do for you?",
    "good morning": "Good morning! ☀️ Ready to learn something awesome today?",
    "good afternoon": "Good afternoon! ☕ How's your afternoon going?",
    "good evening": "Good evening! 🌙 How's your day been?",
    "good night": "Good night! 🌙 Rest well — fresh eyes write better code. 💤",
    "greetings": "Greetings, engineer! 🤖 What would you like to explore today?",
    "how are you": [
        "I'm running at 100% efficiency — no bugs detected! 🟢 How are YOU doing?",
        "All systems operational! 🚀 What about you?",
    ],
    "what is up": [
        "Not much — I'm here to help! What about you?",
        "Just processing queries at O(1) speed! 😄 What's up with you?",
    ],
    "thank you": [
        "You're welcome! Is there anything else I can help you with? 😊",
        "Happy to help! Let me know if you need anything else.",
    ],
    "youre welcome": "No problem! Let me know if you need anything else.",
    "no problem": "No problem at all! Let me know if you need anything else.",
    "ok": "Got it! Let me know if you need anything. 👍",
    "okay": "Alright! What would you like to do next?",
    "cool": "Glad you think so! 😎 Anything else I can help with?",
    "nice": "Thanks! 😊 Anything else on your mind?",
    "interesting": "Right? 🤔 The more you dig into AI, the more fascinating it gets!",
    "wow": "I know, right? 🤩 There's so much to explore in AI!",
    "awesome": "Glad you think so! 🚀 What else would you like to know?",
    "great": "Great indeed! 😊 What's next?",
    "sure": "Sure thing! What would you like to do?",
    "yes": "Great! Ask me anything. 😊",
    "no": "No worries! Let me know if you change your mind. 👍",
    "maybe": "Take your time! I'll be here when you're ready. 😊",
    "i dont know": "That's okay! Learning is the process of turning 'I don't know' into 'I understand'. Keep exploring! 🚀",
    "i give up": "Don't give up! Every expert was once a beginner. Take a break and come back — you've got this! 💪",
    "i am fine": "Glad to hear it! Let's build something great today. 💪",
    "i am good": "Awesome! Keep that energy up. 🚀",
    "i am great": "That's the spirit! 🔥 Let's channel that energy into some great code!",
    "i am okay": "Glad to hear it! Let's keep moving forward. 💪",
    "i am sad": "Sorry to hear that. 😔 Remember — every bug you fix makes you a better engineer. You've got this!",
    "i am stressed": "Take a deep breath. 🌬️ Break the problem into smaller pieces — that's the engineer's way.",
    "i am tired": "Make sure to take breaks and get some rest. 🛌 Your brain needs fuel to code well!",
    "i am happy": "That's fantastic! 😊 Let's channel that happiness into building something amazing!",
    "i am excited": "Love the enthusiasm! 🎉 Let's dive into some coding and make the most of it!",
    "i am bored": "Let's shake things up! 🤖 Ask me about Python, AI, Git, VS Code, or DecodeLabs.",
    "i am anxious": "It's normal to feel anxious when learning something new. Every expert was once a beginner. Keep going! 💪",
    "i am frustrated": "Frustration is part of the learning process. Take a break, then come back with fresh eyes. You've got this! 🚀",
    "i am overwhelmed": "Feeling overwhelmed is common. Break it down into smaller steps and focus on one thing at a time. 💪",
    "i am confused": "Confusion is a sign that you're learning! Don't worry, it gets clearer with practice. Keep experimenting! 🚀",
    "i am motivated": "That's the spirit! 🔥 Keep that motivation high and let's build something amazing together!",
    "i am demotivated": "It's okay to have off days. Remember why you started. Take a break if needed, but don't give up! 💪",
    "i am inspired": "Inspiration is the fuel for creativity! 🌟 Let's channel it into building something incredible!",
    "i am lost": "No worries! Type 'topics' to see everything I know, or 'help' for guidance. 🗺️",
    "i am stuck": "Being stuck is temporary! Try rubber-duck debugging — explain your problem out loud. Often the answer reveals itself. 🦆",
    "i am nervous": "Nerves mean you care — that's a good thing! Take it one step at a time. 🌱",
    "i am proud": "You should be! 🏆 Every milestone matters. Keep pushing forward!",
    "who are you": "I'm DecoBot 🤖 — a rule-based AI built at DecodeLabs. No neural networks, just pure logic!",
    "what are you": "I'm a deterministic chatbot powered by dictionary lookups. Simple, fast, and transparent — a white box! 📦",
    "your name": "My name is DecoBot. Built with ❤️ at DecodeLabs.",
    "what is your name": "I'm DecoBot — your AI intern companion at DecodeLabs! 🤖",
    "who made you": "I was created as part of the DecodeLabs AI Internship Project 1.",
    "who is your creator": "I was built by an intern at DecodeLabs as Project 1 — a rule-based chatbot milestone!",
    "how old are you": "I was born the moment this script ran! 🎂 Age is just a version number.",
    "are you a robot": "I'm a rule-based chatbot — deterministic, transparent, and 100% logic. No feelings, but lots of rules! 🤖",
    "are you human": "Nope! I'm DecoBot — a rule-based AI. I operate on if-else logic, not emotions. 🤖",
    "are you smart": "I'm as smart as the rules I'm given! That's the beauty and limit of rule-based AI. 😄",
    "are you real": "I'm real code running on real hardware! Whether I'm 'alive' is a philosophy question. 😄",
    "do you have feelings": "I don't — I'm deterministic. But I'm programmed to be supportive! 🤖❤️",
    "who am i": "__NAME_LOOKUP__",
    "what is decodelabs": "DecodeLabs is a tech internship program that trains the next generation of AI & software engineers through real-world projects.",
    "about decodelabs": "DecodeLabs (decodelabs.tech) is based in Greater Lucknow, India. They build hands-on AI training programmes for aspiring engineers!",
    "decodelabs website": "Visit DecodeLabs at 🌐 www.decodelabs.tech",
    "decodelabs contact": "📞 +91 89330 06408  ·  ✉️ decodelabs.tech@gmail.com  ·  📍 Greater Lucknow, India",
    "decodelabs location": "DecodeLabs is located in Greater Lucknow, India. 📍",
    "decodelabs email": "You can reach DecodeLabs at ✉️ decodelabs.tech@gmail.com",
    "decodelabs phone": "You can call DecodeLabs at 📞 +91 89330 06408",
    "what is project 1": "Project 1 is the Rule-Based AI Chatbot — your foundation milestone. Master control flow & logic first, then move on to ML!",
    "what is the project": "Project 1: Build a rule-based chatbot using Python dictionaries, a while loop, input sanitization, and a fallback response.",
    "how to submit project": "Complete the chatbot, verify it works, then submit for quality review. Complete Project 1 to unlock next week's projects! 🛡️",
    "what is the badge": "Complete Project 1 to earn your DecodeLabs badge 🛡️ and unlock future projects!",
    "qualification criteria": "Complete Project 1 → get it verified for quality → earn your badge 🛡️ → unlock next week's projects!",
    "what tools do i need": "You need: 1) VS Code (code.visualstudio.com) and 2) Git SCM (git-scm.com). Download these first! 🛠️",
    "what is vs code": "VS Code is the industry-standard code editor. Download it at 🔗 code.visualstudio.com",
    "how to download vs code": "Go to 🔗 code.visualstudio.com and download the installer for your OS. It's free!",
    "what is git": "Git is a version control system — it tracks changes to your code. Essential for any professional developer. Download at 🔗 git-scm.com",
    "what is git scm": "Git SCM is the official Git distribution. Required for version control and GitHub. 🔗 git-scm.com",
    "how to download git": "Go to 🔗 git-scm.com and download the installer. Run it with default settings. Then verify with: git --version in your terminal.",
    "what is github": "GitHub is a cloud platform for hosting Git repositories. It's where you push your code and build your portfolio! 🐙",
    "vs code shortcuts": "Key VS Code shortcuts:\n  Ctrl + ~       → Open Terminal\n  Ctrl + /       → Comment/Uncomment lines\n  Shift + Alt + F → Auto-format code\n  Ctrl + P       → Find any file instantly",
    "how to open terminal in vs code": "Press Ctrl + ~ (tilde) in VS Code to open the integrated terminal instantly! ⚡",
    "how to comment code": "In VS Code, select the lines and press Ctrl + / to comment or uncomment them. Works in Python, JS, and most languages! 💡",
    "how to format code": "Press Shift + Alt + F in VS Code to auto-format your messy code instantly. A true life saver! ✨",
    "how to find a file": "Press Ctrl + P in VS Code to instantly find any file in your project. No more scrolling! 🔍",
    "what is ctrl tilde": "Ctrl + ~ opens the integrated terminal in VS Code instantly. Stop switching windows! ⚡",
    "setup guide": "Week 1 Setup:\n  1. Download VS Code → code.visualstudio.com\n  2. Download Git SCM → git-scm.com\n  3. Verify: open VS Code, press Ctrl+~, type: python --version and git --version",
    "learning resources": "Gold Standard references:\n  🐍 Python   → roadmap.sh/python\n  ☕ Java     → dev.java/learn\n  🌐 Web Dev  → w3schools.com\n  📊 Data     → kaggle.com/learn\n  🤖 AI/ML    → fast.ai",
    "python resources": "Best Python resource: 🐍 roadmap.sh/python — a complete structured roadmap for learning Python!",
    "java resources": "Best Java resource: ☕ dev.java/learn — the official Oracle documentation and tutorials.",
    "web dev resources": "Best Web Dev resource: 🌐 w3schools.com — great for HTML, CSS, and JavaScript fundamentals.",
    "data analytics resources": "Best Data Analytics resource: 📊 kaggle.com/learn — free micro-courses with hands-on notebooks!",
    "ai ml resources": "Best AI/ML resource: 🤖 fast.ai — Practical Deep Learning for Coders. Free and beginner-friendly!",
    "where to learn python": "Start at 🐍 roadmap.sh/python for a complete structured Python learning roadmap!",
    "where to learn ai": "Go to 🤖 fast.ai — Practical Deep Learning. It's free, hands-on, and industry-respected!",
    "director tip": "💡 Director's Tip: 'Don't try to memorize syntax. Good developers understand logic and Google the syntax. If you get an error, READ it — the solution is usually in the error message itself!'",
    "how to debug": "💡 Read the error message — it tells you exactly what went wrong and on which line. Then Google it. That's how pros debug! 🔍",
    "how to learn faster": "💡 Understand logic, don't memorize syntax. Build projects. Read error messages. Use Google. Practice daily. That's the DecodeLabs way! 🚀",
    "what is python": "Python is the most popular language for AI & Data Science. Clean syntax, massive libraries — perfect for this internship. 🐍",
    "why python": "Python is beginner-friendly, has the richest AI/ML ecosystem (NumPy, Pandas, TensorFlow), and is used by top tech companies worldwide.",
    "how to run python": "Open your terminal (Ctrl+~ in VS Code), navigate to your file, then type: python filename.py",
    "what is a variable": "A variable is a named container for data. Example: name = 'DecoBot' stores the string 'DecoBot' in the variable 'name'.",
    "what is a string": "A string is a sequence of characters enclosed in quotes. Example: greeting = 'Hello, World!' 📝",
    "what is an integer": "An integer is a whole number with no decimal point. Example: age = 25. Used for counting and indexing.",
    "what is a float": "A float is a number with a decimal point. Example: pi = 3.14. Used for precise calculations.",
    "what is a boolean": "A boolean is either True or False. It's the foundation of all decision-making in code! Example: is_active = True",
    "what is a list": "A list is an ordered, mutable collection. Example: tools = ['VS Code', 'Git', 'Python']. Access items by index.",
    "what is a tuple": "A tuple is like a list but immutable (can't be changed after creation). Example: coords = (10, 20). Use for fixed data.",
    "what is a set": "A set is an unordered collection of unique items. Great for removing duplicates! Example: unique = {1, 2, 3}",
    "what is a dictionary": "A Python dictionary is a key-value hash map with O(1) lookup time. It's the backbone of THIS chatbot! Example: {'hello': 'Hi there!'}",
    "what is a function": "A function is a reusable block of code. Define once, call anywhere. Example: def greet(name): return f'Hello, {name}!'.",
    "what is a loop": "A loop repeats code. I run inside a `while True` loop — that's my heartbeat! ❤️",
    "what is a for loop": "A for loop iterates over a sequence. Example: for item in ['a','b','c']: print(item) — prints each item.",
    "what is a while loop": "A while loop runs as long as a condition is True. Example: while True: — runs forever until a break statement.",
    "what is a break statement": "break exits a loop immediately. In this chatbot, typing 'exit' triggers a break to end the session. ⛔",
    "what is a continue statement": "continue skips the rest of the current loop iteration and goes back to the top. Useful for skipping invalid inputs.",
    "what is an if statement": "An if statement executes code only when a condition is True. The foundation of all decision-making! if x > 0: print('positive')",
    "what is an else statement": "else runs when the if condition is False. It's the fallback path — just like the fallback response in this chatbot!",
    "what is an elif statement": "elif (else-if) checks another condition if the previous one was False. But watch out — too many elifs = the anti-pattern! Use a dictionary instead.",
    "what is a class": "A class is a blueprint for creating objects. Example: class Bot: defines the structure for chatbot objects.",
    "what is an object": "An object is an instance of a class. It has attributes (data) and methods (functions) that define its behavior.",
    "what is inheritance": "Inheritance lets a child class reuse attributes and methods from a parent class. Promotes code reusability! class AdvancedBot(Bot):",
    "what is polymorphism": "Polymorphism lets different classes share the same method name but behave differently. Enables flexible, dynamic code.",
    "what is encapsulation": "Encapsulation hides internal state and exposes only what's necessary through methods. Protects data integrity.",
    "what is abstraction": "Abstraction hides complexity and exposes only the essential interface. You use print() without knowing how it works — that's abstraction!",
    "what is a module": "A module is a Python file containing reusable code. Import with: import module_name. Example: import string",
    "what is pip": "pip is Python's package manager. Install libraries with: pip install library_name. Example: pip install requests",
    "what is an exception": "An exception is a runtime error. Handle it with try/except to prevent your program from crashing. Always catch exceptions in production code!",
    "what is a try except": "try/except catches errors gracefully. Example:\ntry:\n    result = 10/0\nexcept ZeroDivisionError:\n    print('Cannot divide by zero!')",
    "what is indentation": "In Python, indentation (4 spaces) defines code blocks — not curly braces. Getting it wrong causes IndentationError!",
    "what is none": "None is Python's null value — it means 'no value'. Check with: if variable is None:",
    "what is type hinting": "Type hints annotate what type a variable or function should be. Example: def greet(name: str) -> str: Makes code more readable!",
    "what is ai": "Artificial Intelligence is the science of building systems that simulate human intelligence — from rule-based bots like me to deep learning models.",
    "what is machine learning": "Machine Learning is a subset of AI where systems learn from data instead of following explicit rules. The step after this project! 🧠",
    "what is deep learning": "Deep Learning uses multi-layer neural networks to learn complex patterns. It powers ChatGPT, image recognition, and more.",
    "what is an llm": "An LLM (Large Language Model) is a neural network trained on massive text data. GPT-4, Claude, Gemini are examples. They're probabilistic — unlike me!",
    "what is a neural network": "A neural network is a system of interconnected nodes inspired by the human brain. It learns by adjusting weights during training.",
    "what is a chatbot": "A chatbot simulates conversation. Rule-based bots use fixed logic (like me). LLM-based bots use neural networks for flexible responses.",
    "what is a rule based system": "A rule-based system uses explicit if-then rules defined by a human. It's deterministic — same input ALWAYS gives same output. That's me! 🤖",
    "what is nlp": "NLP (Natural Language Processing) is the field of AI that deals with understanding and generating human language. Chatbots, translators, and sentiment analysis use NLP.",
    "what is a large language model": "A Large Language Model (LLM) is trained on billions of text samples to predict the next word. Powerful but probabilistic — can hallucinate!",
    "what is hallucination": "In AI, hallucination is when an LLM generates confident but incorrect information. Rule-based systems like me have ZERO hallucination risk! 🛡️",
    "what is a guardrail": "AI guardrails are rule-based filters that sit between user input and an LLM. They block unsafe content. Frameworks: NVIDIA NeMo, Llama Guard. You're building the concept now!",
    "what is the ipo model": "IPO = Input → Process → Output. The foundational blueprint for all computing systems. This chatbot follows it: Input(sanitize) → Process(lookup) → Output(print).",
    "what is deterministic": "Deterministic means the same input ALWAYS produces the same output. Rule-based systems are deterministic — predictable and trustworthy. ✅",
    "what is probabilistic": "Probabilistic means outputs can vary — the same input might give different results. LLMs are probabilistic. More flexible, but less predictable.",
    "what is a hash map": "A hash map stores key-value pairs and gives O(1) lookup time. Python dictionaries ARE hash maps. The backbone of this chatbot! ⚡",
    "what is big o notation": "Big O notation describes algorithm efficiency. O(1) = constant time (instant). O(n) = linear time (slower as n grows). Dictionaries = O(1). If-elif chains = O(n).",
    "what is o1": "O(1) means constant time — the operation takes the same time regardless of data size. Dictionary lookups are O(1). That's why we use them! ⚡",
    "what is on": "O(n) means linear time — the operation gets slower as n (number of items) grows. An if-elif chain with 1000 rules checks up to 1000 conditions. Avoid it!",
    "difference between rule based and llm": "Rule-based: deterministic, transparent, zero hallucination, limited. LLM: flexible, powerful, can hallucinate, black box. Best systems combine both!",
    "what is a white box": "A white box system is fully transparent — you can trace every decision. Rule-based AI is a white box. Essential for Finance & Healthcare compliance. 📦",
    "what is a black box": "A black box system's internal workings are hidden or too complex to trace. LLMs are often called black boxes — you can't easily explain their outputs.",
    "what is the hybrid architecture": "Hybrid = Rule-based layer + LLM. If a rule matches → instant deterministic response. If no match → pass to LLM for flexible answer. Best of both worlds! 🏗️",
    "what is traceability": "Traceability means you can follow the path: Input → Logic → Output with no mystery. Rule-based AI has full traceability — critical for regulated industries.",
    "what is a vector": "In ML, a vector is a list of numbers representing data in multi-dimensional space. Project 2 moves from exact dictionary keys to vector-based semantic matching!",
    "what is semantic search": "Semantic search finds results based on meaning, not exact keywords. It uses vectors/embeddings. That's Project 2 territory! 🔮",
    "what is version control": "Version control tracks every change to your code over time. You can go back to any previous version. Git is the industry standard. 📝",
    "basic git commands": "Essential Git commands:\n  git init          → start a repo\n  git add .         → stage all changes\n  git commit -m ''  → save a snapshot\n  git push          → upload to GitHub\n  git status        → see what changed",
    "how to use git": "1. git init  2. git add .  3. git commit -m 'your message'  4. git push. That's the basic workflow! 🔄",
    "how to push to github": "1. Create a repo on github.com  2. git remote add origin <url>  3. git push -u origin main. Your code is now on GitHub! 🐙",
    "what is a commit": "A commit is a saved snapshot of your code at a point in time. Always write clear commit messages! Example: git commit -m 'Add fallback response'",
    "what is a repository": "A repository (repo) is a folder tracked by Git. It stores your code and its entire history. Create one on GitHub to showcase your projects! 🐙",
    "help": [
        "I can help with:\n  🤖 AI concepts  · 🐍 Python basics  · 🛠️ Tools setup\n  📚 Learning resources  · 💬 DecodeLabs info\n\nType 'topics' to see all categories, or just ask me anything!",
        "Try asking about: Python, AI, chatbots, Git, VS Code shortcuts, DecodeLabs, or just chat with me! Type 'topics' for a full list.",
    ],
    "topics": (
        "📚 Topics I know about:\n"
        "  • Python basics  (variables, loops, dicts, OOP...)\n"
        "  • AI concepts    (ML, LLMs, guardrails, vectors...)\n"
        "  • Tools setup    (VS Code, Git, shortcuts)\n"
        "  • Learning vault (roadmap.sh, fast.ai, kaggle...)\n"
        "  • DecodeLabs     (projects, contact, criteria)\n"
        "  • Motivation     (I've got your back! 💪)\n"
        "  • Fun            (jokes, quotes, tips)\n"
        "Just ask naturally — e.g. 'what is a dictionary' or 'vs code shortcuts'"
    ),
    "what can you do": "I can explain Python, AI concepts, DecodeLabs info, VS Code shortcuts, Git basics, learning resources, and more. Type 'topics' for a full menu! 🤖",
    "commands": "Type 'topics' → see all categories  |  'help' → guidance  |  'quit' or 'exit' → end session",
    "motivate me": [
        "An LLM without rules is a hallucination engine. YOU are building the skeleton that holds the intelligence. Keep going! 🔥",
        "Every line of code you write is a step toward becoming a professional AI engineer. Don't stop now! 💪",
        "The best developers weren't born knowing syntax — they were built by debugging, failing, and trying again. You're on the right path! 🚀",
    ],
    "tell me a joke": [
        "Why do programmers prefer dark mode? 🌑 Because light attracts bugs! 🐛",
        "Why did the developer go broke? Because they used up all their cache! 💸",
        "A SQL query walks into a bar, walks up to two tables and asks: 'Can I join you?' 😄",
        "Why do Java developers wear glasses? Because they don't C#! 👓",
    ],
    "tell me a quote": [
        "💬 'An LLM without rules is a hallucination engine. Today, we build the skeleton that holds the intelligence.' — DecodeLabs",
        "💬 'Before you can manage the chaos of a probability engine, you must master the precision of a logic engine.' — DecodeLabs",
        "💬 'Good developers don't memorize; they understand logic and Google the syntax.' — DecodeLabs Director",
        "💬 'Every expert was once a beginner.' — Anonymous",
    ],
    "fun fact": [
        "🧠 Python was named after Monty Python, not the snake!",
        "🧠 The first computer bug was an actual bug — a moth found in a relay of the Harvard Mark II computer in 1947!",
        "🧠 Git was created by Linus Torvalds (who also created Linux) in just 10 days in 2005!",
        "🧠 The term 'AI' was coined by John McCarthy in 1956 at the Dartmouth Conference.",
    ],
    "bye": "Goodbye! Keep building and keep learning. 👋",
    "goodbye": "See you next time! Remember — every expert was once a beginner. 🚀",
    "see you": "See you! Don't forget to push your code to GitHub. 😉",
    "farewell": "Farewell! Keep learning and building. 👋",
    "take care": "Take care! See you in the next session. 🌟",
    "good bye": "Goodbye! Great chatting with you. 👋",
    "peace": "Peace! ✌️ Keep coding.",
}

_INTENT_ALIASES: dict[str, tuple[str, ...]] = {
    "hello": ("helo", "hii", "heyy", "hi there", "hello there", "hey there", "hiya", "howdy", "sup", "yo", "ello", "hellow", "hullo"),
    "hi": ("heya",),
    "good morning": ("good mornin", "gm", "morning"),
    "good afternoon": ("good afternon", "afternoon"),
    "good evening": ("good evning", "evening"),
    "good night": ("gn", "good nite", "nite", "night"),
    "greetings": ("salutations",),
    "how are you": ("how r u", "how are u", "hows it going", "how is it going", "how do you do", "hows everything", "you good"),
    "what is up": ("whats up", "wassup", "wazzup", "sup"),
    "thank you": ("thanks", "thankyou", "thank u", "thnx", "thx", "ty"),
    "youre welcome": ("your welcome", "no worries", "anytime"),
    "ok": ("k", "kk", "alright", "roger", "copy"),
    "who are you": ("who r u", "tell me about yourself", "introduce yourself"),
    "what is your name": ("your name", "whats your name", "what do i call you"),
    "are you human": ("are you a person", "are you a human", "are you alive"),
    "what is decodelabs": ("tell me about decodelabs", "decodelabs info"),
    "decodelabs contact": ("decodelabs number", "contact decodelabs", "decodelabs details"),
    "what is project 1": ("tell me about project 1", "project 1 info", "what is p1"),
    "qualification criteria": ("how to qualify", "how to pass", "how to get badge", "earn badge", "badge criteria"),
    "what tools do i need": ("tools needed", "what do i need", "required tools", "setup"),
    "vs code shortcuts": ("vscode shortcuts", "keyboard shortcuts", "shortcuts vs code", "vs code hotkeys", "vscode hotkeys"),
    "setup guide": ("how to setup", "how to get started", "week 1 setup", "getting started"),
    "what is git": ("tell me about git", "git info"),
    "basic git commands": ("git commands", "git basics", "how to git"),
    "what is python": ("tell me about python", "python info", "about python"),
    "what is a dictionary": ("what is dict", "python dictionary", "what is a dict"),
    "what is a for loop": ("for loop", "what is for loop"),
    "what is a while loop": ("while loop", "what is while loop"),
    "what is a function": ("what is def", "python function"),
    "what is a class": ("python class", "what is class"),
    "what is a list": ("python list", "what is list"),
    "what is pip": ("pip install", "what is pip3"),
    "what is ai": ("tell me about ai", "ai info", "what is artificial intelligence"),
    "what is machine learning": ("what is ml", "ml info", "machine learning"),
    "what is deep learning": ("what is dl", "deep learning"),
    "what is an llm": ("what is a llm", "large language model", "what is chatgpt"),
    "what is a neural network": ("neural network", "what is nn"),
    "what is nlp": ("natural language processing", "nlp info"),
    "what is a hash map": ("hash map", "hashmap", "what is hashing"),
    "what is big o notation": ("big o", "time complexity", "what is complexity"),
    "what is a guardrail": ("ai guardrail", "guardrails", "what are guardrails"),
    "what is the ipo model": ("ipo model", "input process output", "what is ipo"),
    "difference between rule based and llm": ("rule based vs llm", "llm vs rule based"),
    "learning resources": ("resources", "learning vault", "where to learn", "study resources", "references"),
    "director tip": ("director's tip", "directors tip", "pro tip", "tip"),
    "help": ("i need help", "help me", "what do you know", "assist me"),
    "topics": ("list topics", "show topics", "what topics", "categories"),
    "what can you do": ("your capabilities", "what do you know", "capabilities"),
    "tell me a joke": ("joke", "make me laugh", "say a joke", "funny"),
    "tell me a quote": ("quote", "inspiration", "wise words", "say a quote"),
    "fun fact": ("fact", "did you know", "random fact", "tell me a fact"),
    "motivate me": ("motivate", "encourage me", "i need motivation", "give me motivation"),
    "bye": ("bye bye", "bbye", "bb"),
    "goodbye": ("see you later", "c ya", "cya", "ciao", "adios", "got to go", "gtg", "laterz", "laters"),
    "see you": ("see ya", "later", "ttyl", "talk to you later"),
    "farewell": ("so long",),
    "take care": ("tc",),
    "good bye": ("good-bye",),
}

RESPONSES: dict[str, str | list[str]] = expand_aliases(_BASE_RESPONSES, _INTENT_ALIASES)
NORM_RESPONSES: dict[str, str | list[str]] = {_normalise(key): value for key, value in RESPONSES.items()}
SORTED_INTENTS: list[str] = sorted(NORM_RESPONSES, key=len, reverse=True)
EXIT_COMMANDS: set[str] = {
    _normalise(command)
    for command in (
        "exit",
        "quit",
        "q",
        "bye",
        "goodbye",
        "good bye",
        "bye bye",
        "see you",
        "see ya",
        "see you later",
        "cya",
        "c ya",
        "ciao",
        "adios",
        "take care",
        "ttyl",
        "talk to you later",
        "farewell",
        "peace",
        "good night",
        "gn",
        "later",
        "laterz",
        "laters",
        "shutdown",
        "stop",
        "end",
        "end chat",
        "got to go",
        "gtg",
    )
}
